project:
  type: website
  output-dir: docs

website:
  title: "Nicole M. Greco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full


