project:
  type: website
  output-dir: docs

website:
  title: "Nicole M. Greco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd
      - publications.qmd

format:
  html:
    theme:
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

