---
title: "Professional Experience"
---

**Conference Presentation** – Toolik All Scientists Meeting, January 2025

• Held a workshop on *Ethical Principles for Open-Access Data* for the Toolik Field Station research community.

**Conference Presentation** – Earth Science Information Partners Winter Meeting, January 2025

• Co-presented on *Data Management Plans and Ethical Research Practices at the Arctic Data Center*.

**Webinar** – Interagency Arctic Research Policy Committee Collaboration’s Arctic Data and Indigenous Data Sovereignty Series, November 2024

• Presented on *Implementing CARE: Best Practices for Ethical Research and Sensitive Data Documentation at the Arctic Data Center*.

**Sedimentology Field Experience** – International Ocean Discovery Program Expedition 403, June-August, 2024

• Sailed on IODP Expedition 403 as a sedimentologist with the goal of reconstructing the paleo Svalbard-Barents Sea Ice Sheet and associated bottom currents off the coast of West Svalbard.

**Glacial Sedimentation School** (GLASS) – Oregon State University Marine and Geology Repository, May 2022

• Studying Antarctic and Greenland sediment cores at OSU-MGR to interpret past climate.

**Invited Seminar** – Oregon State University Quat-Tea, November 2021

• Presented my doctoral research on *Deciphering the Role of Meltwater in the Formation of Gulf of Alaska Sediments*.

**Geology Field Camp** – Ireland, May 2019- June 2019 (6 weeks study abroad)\
• Large Scale Independent Mapping Project

• Digital Mapping and Road Cut Analysis

• Glacial Movement Mapping

• Hydrology
